import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getFirestore, collection, addDoc, deleteDoc, doc, onSnapshot, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyAgmqA4hSPq8WgeSLOj2RpxDZqETvZox6E',authDomain:'zhanna-sbirthday.firebaseapp.com',projectId:'zhanna-sbirthday',storageBucket:'zhanna-sbirthday.firebasestorage.app',messagingSenderId:'80653580579',appId:'1:80653580579:web:c4e29eb1e2738f60987496'};
const ADMIN_EMAILS=['']; // Put the Firebase Authentication email(s) allowed to manage this site here.
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=s=>document.querySelector(s);
function authorized(user){return user&&ADMIN_EMAILS.includes(user.email?.toLowerCase());}
onAuthStateChanged(auth,user=>{const ok=authorized(user);$('#login').hidden=ok;$('#control').hidden=!ok;if(user&&!ok){signOut(auth);$('#loginError').textContent='Цей обліковий запис не має доступу.';}});
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{await signInWithEmailAndPassword(auth,$('#email').value,$('#password').value);}catch{ $('#loginError').textContent='Не вдалося увійти. Перевір email і пароль.';}});$('#signOut').addEventListener('click',()=>signOut(auth));
function bindForm(id,collectionName,transform=(data)=>data){$(id).addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const raw=Object.fromEntries(new FormData(form));try{await addDoc(collection(db,collectionName),{...transform(raw),createdAt:serverTimestamp()});form.reset();alert('Збережено');}catch{alert('Не вдалося зберегти. Перевір Firestore Rules.');}});}
bindForm('#newsForm','news');bindForm('#routeForm','transport',d=>({...d,recommended:d.recommended==='on',bookingUrl:'https://booking.uz.gov.ua/'}));bindForm('#locationForm','restaurants',d=>({...d,photos:d.photos?d.photos.split(',').map(v=>v.trim()).filter(Boolean).slice(0,3):[]}));
let photos=0,votes=0;onSnapshot(collection(db,'gallery'),s=>{photos=s.size;$('#stats').textContent=`Фото: ${photos} · Голосів: ${votes}`;$('#adminPhotos').innerHTML=s.docs.map(d=>`<article><img src="${d.data().previewUrl||d.data().url}" alt=""><button data-id="${d.id}" aria-label="Видалити фото">×</button></article>`).join('');$('#adminPhotos').querySelectorAll('button').forEach(b=>b.addEventListener('click',async()=>{if(confirm('Прибрати фото з галереї?'))await deleteDoc(doc(db,'gallery',b.dataset.id));}));});onSnapshot(collection(db,'votes'),s=>{votes=s.size;$('#stats').textContent=`Фото: ${photos} · Голосів: ${votes}`;});
